name: Regressions

on:
  schedule:
    - cron: "23 10 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  loom:
    name: Loom model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        run: rustup toolchain install stable --profile minimal

      - name: Test loom model
        run: cargo +stable test --locked --features loom --test thread_safe_loom

